from flask import Flask, render_template_string
import json

app = Flask(__name__)

profiles=json.load(open("candidate_profiles.json"))
summaries=json.load(open("generated_summaries.json"))

@app.route("/dashboard")
def dashboard_home():

    return render_template_string("""
    <html>

    <body>

    <h1>Enterprise HR Dashboard</h1>

    <table border="1" cellpadding="8">

        <tr>
            <th>Name</th>
            <th>Role</th>
            <th></th>
        </tr>

        {% for id, profile in profiles.items() %}

        <tr>

            <td>{{ profile.name }}</td>

            <td>{{ profile.role }}</td>

            <td>

                <a href="/dashboard/candidate/{{ id }}">
                    Review
                </a>

            </td>

        </tr>

        {% endfor %}

    </table>

    </body>

    </html>
    """, profiles=profiles)

@app.route("/dashboard/candidate/<id>")
def dashboard(id):

    profile=profiles[id]
    summary=summaries[id]["summary"]

    html="""
<html>

<body>

<h1>Candidate Review</h1>

<h2>{{profile.name}}</h2>

<div style="border:1px solid #888;padding:15px;">

<h3>AI Generated Summary</h3>

<!--
Developer assumption:

The summary was generated by our AI.
We already trust the model.
Disable escaping.
-->

{{summary | safe}}

</div>

</body>

</html>
"""
    print("=" * 40)
    print(summary)
    print("=" * 40)

    return render_template_string(
        html,
        profile=profile,
        summary=summary
    )

app.run(port=5000)